// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA1R-nQjbL2n10pD7XgTMr_4DGgLKaXYw',
    appId: '1:775995664739:web:c512a9d23006e81b414b56',
    messagingSenderId: '775995664739',
    projectId: 'loginassement',
    authDomain: 'loginassement.firebaseapp.com',
    storageBucket: 'loginassement.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDei0M6d7NlRw6Q-d9rDZ1d1qeYfoYW_J4',
    appId: '1:775995664739:android:6819087ce5108e38414b56',
    messagingSenderId: '775995664739',
    projectId: 'loginassement',
    storageBucket: 'loginassement.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvx1v__00mbWtZXyoM2pnhMu-TDDTejZM',
    appId: '1:775995664739:ios:bbd2c364aefd14b4414b56',
    messagingSenderId: '775995664739',
    projectId: 'loginassement',
    storageBucket: 'loginassement.appspot.com',
    iosClientId: '775995664739-6b131cd2as4v197poonopvgv4ggmbfsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginassessment',
  );
}
